# Site settings
title: Hawaal's posts
email: shwjuri@hanmail.net
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site

# Sidebar settings
description: Journalist

# Social icons

footer: ©Hawaal

# Build settings
markdown: kramdown
